### ISSUE TITLE
Implemented alerts

### ISSUE THREAD

**Issue by ViniciusDeep** [ViniciusDeep/Tetris-Game#1]
Set alerts where event of game over

**Comment by valentinaperic** [comment]
I can work on this! :)

**Comment by ViniciusDeep** [comment]
Ohhh nice.
Thanks!

**Comment by quintanilhaedu** [comment]
Man, do you have other issues? I can help in your project. 👍

**Comment by ViniciusDeep** [comment]
You can implemented score, i will created another issue for this.

**Comment by ViniciusDeep** [comment]
I will create the new issues

**Comment by ViniciusDeep** [comment]
You can stay in charge of alerts?
